= Add Modules to Your Project
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can add Modules and Connectors to your Mule project using the Mule Palette.

If you're editing a Mule Application project:

. Go to your Mule Palette, and click the Search in Exchange... option.
+
By default, this list shows the available public modules. If you configured your Anypoint Platform credentials in Studio, you can also see your organization's private modules. +
If you have no credentials configured in Studio, you can click Add Account to access your organization's modules.
. Select your desired modules from the Available Modules list by clicking Add >.
. Click Finish.

The selected module is now part of your Mule Palette.

Additionally, you can also select the Add Modules option, and drag your desired module from the featured list.

Modules are dependencies of your Mule project. Adding a module to a Mule project in Studio does not make that module available to other projects in your Studio workspace. +

If you're editing a Mule Domain project:

. Go to the Global Elements tab from your Mule Domain configuration editor and click Manage Modules.
. Click Add Module.
+
By default, this list shows the available public modules. If you configured your Anypoint Platform credentials in Studio, you can also see your organization's private modules. +
If you have no credentials configured in Studio, you can click Add Account to access your organization's modules.
. Select your desired modules from the Available Modules list by clicking Add >.
. Click Finish.

The selected Module is now part of your Mule Domain and it shows up in the Mule Palette of the Mule Application.

[NOTE]
Modules inherited by a Mule domain show as such in the Mule Palette View. +
You can't edit or delete Domain Modules from your Mule Application's palette.

== See Also

* xref:add-custom-modules-in-studio-to.adoc[To Add Custom Modules to Your Project]
* xref:set-credentials-in-studio-to.adoc[To Configure Anypoint Platform Credentials]
