= API Sync
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: api, anypoint platform, sync, api sync

The API Sync feature of Anypoint Studio enables you to:

* Start designing a RAML, or OAS 2.0 and 3.0 API specification in Studio and synchronize it with Design Center.
* Pull a published RAML or OAS 2.0 and 3.0 API specification from Exchange or a private Maven repository, into your Mule application project in Studio to scaffold a new project. +
API sync also enables you to edit the API specification you imported from Exchange, and push your changes to Design Center.
+
You can use API Sync on more than one API specification to scaffold multiple flows in different Mule configuration files.
* Monitor the API versions that you implemented in your project and update your flows based on the latest published version.
* Pull a RAML or OAS 2.0 and 3.0 API specification from Design Center into Studio, edit the specification offline, and pull the updates back to Design Center.

API Sync supports importing both RAML, OAS 2.0 and OAS 3.0 specifications.

API Sync comes bundled by default in Studio 7.4.x and later, and requires Mule 4.1.4 and later.

API sync might not work properly if the RAML file exceeds 4,000 lines of text.

Using API Sync, you can develop your Mule applications following API Lifecycle development practices.

== Create an API Specification in Studio

. Start a new API specification project in Studio.
See xref:create-api-specification-studio.adoc[Create an API Specification Project in Studio] for more information.
. Publish it to Exchange.
. Import the same API specification from Exchange to your Studio project. +
See xref:import-api-specification-exchange.adoc[Importing an API Specification from Exchange] for more information.

== Import an API Specification from Exchange into a New Mule Project

. Create an API specification in Design Center. +
You can either xref:design-center::design-create-publish-api-raml-editor.adoc[Create an API Specification with the Text Editor in Design Center] or xref:design-center::design-create-publish-api-visual-editor.adoc[Create an API Specification with the Visual API Editor in Design Center].
. Publish it to Exchange. +
See xref:design-center::design-publish.adoc[Publish an API Specification] for more information.
. Import the same API specification from Exchange to your Studio project. +
See xref:import-api-specification-exchange.adoc[Importing an API Specification from Exchange] for more information.

See xref:sync-update-api-spec.adoc[Update the API Specification in Your Project] for instructions on keeping your Studio projects up to date with to the latest version of an API specification.

=== Edit The Imported API Specification in Studio

You can also edit the imported API specification in your project as an API specification project.

. Import the API specification from Exchange to your Studio project.
. Synchronize it to Design Center,
. Publish it to Exchange
. Import the new version of your API spec.

See xref:sync-imported-api-specifications-design-center.adoc[Edit Imported API Specifications in Your Projects in Studio] for more information.

== Import an API Specification from Design Center into an Editable API Specification Project

. Create an API specification in Design Center. +
You can either xref:design-center::design-create-publish-api-raml-editor.adoc[Create an API Specification with the Text Editor in Design Center] or xref:design-center::design-create-publish-api-visual-editor.adoc[Create an API Specification with the Visual API Editor in Design Center].
. Import the same API specification from Design Center to your Studio project. +
See xref:sync-api-projects-design-center.adoc[Synchronize API Specifications with Design Center] to learn how to do this.

== See Also

* xref:api-development-studio.adoc[API Development in Studio]
* xref:import-api-specification-exchange.adoc[Importing an API Specification from Exchange]
* xref:import-api-specification-maven.adoc[Importing an API Specification from Maven]
