= Sync Your API Projects with API Sync
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: api, anypoint platform, sync, api sync, MuleSoft VCS

With API Sync, you can:

* Start designing a RAML, OAS 2.0, or OAS 3.0 API spec in Studio and sync it with API Sync.
* Pull a published RAML, OAS 2.0, or OAS 3.0 API spec from Exchange or from a private Maven repository, into your Mule application project in Studio to scaffold a new project. 
* Edit the API spec you imported from Exchange, and push your changes to MuleSoft VCS.
* Use API Sync on more than one API spec to scaffold multiple flows in different Mule configuration files.
* Monitor the API versions that you implement in your project and update your flows based on the latest published version.
* Pull a RAML, OAS 2.0, or OAS 3.0 API spec from MuleSoft VCS into Studio, edit the spec offline, and push the updates back to MuleSoft VCS.
* Develop your Mule applications using API lifecycle development practices.

API Sync supports importing both RAML, OAS 2.0, and OAS 3.0 spec, comes bundled by default with Studio, and requires Mule 4.1.4 and later.

API Sync can’t work properly if the RAML file exceeds 4,000 lines of text.

== Create an API Spec in Studio

Start a new API spec project in Studio. See xref:create-api-specification-studio.adoc[] for more information.

== Import an API Spec from Exchange 

Import an API spec from Exchange into a new Mule project or from MuleSoft VCS into an Editable API Spec Project.

See xref:import-api-specification-exchange.adoc[] for more information.

See xref:sync-update-api-spec.adoc[] for more information about keeping your Studio projects up to date with the latest version of an API spec.

See xref:sync-api-projects-design-center.adoc[] for more information.

=== Edit the Imported API Spec in Studio

Edit the imported API spec in your project as an API spec project.

. Import the API spec from Exchange to your Studio project.
. Sync it to MuleSoft VCS.
. Publish it to Exchange.
. Import the new version of your API spec.

See xref:sync-imported-api-specifications-design-center.adoc[] for more information.

== See Also

* xref:api-development-studio.adoc[]
* xref:import-api-specification-exchange.adoc[]
* xref:import-api-specification-maven.adoc[]
