= Breakpoints
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can configure breakpoints according to three parameters set in the Mule Breakpoints View.

[%header,cols="2*"]
|===
|Type |Description
|Default (no parameters) |Default configuration for a user-defined breakpoint. The breakpoint is set on a user-defined event processor, and activated by default. When a message reaches the breakpoint event processor, Studio stops flow execution and displays the contents of the message in the Mule Debugger View.
|Conditional |The breakpoint is activated only if a user-defined condition evaluates to _true_.
// REVIEW Exception to Error breakpoint
|Exception |This is a global parameter. When set, Studio stops flow execution _at any event processor_ where an exception occurs. The Mule Debugger View will display the message contents at the event processor that threw the exception.
|===

When you set a breakpoint, Studio activates the breakpoint by default. The Mule Breakpoints View indicates the activation with a checked box to the left of the breakpoint name. Uncheck the box to deactivate a breakpoint. +
Though deactivated, Studio does not delete the breakpoint. In the canvas, the breakpoint's corresponding event processor displays a gray circle instead of red.

Additionally you can activate the Mute Breakpoints option in the Mule Debugger View, to temporarily disallow the debugger to stop at your selected breakpoints.


