= Publishing a Project to Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio allows you to connect to Exchange to publish your project as a new asset.

. Right-click your project's folder on your Package Explorer view.
. Select *Anypoint Platform* > *Publish to Exchange*.
. Select your Anypoint Platform user and business group. +
Additionally you can click the "Add Account" button to use a new Anypoint Platform account.
. Review the information about your project:
* *Group ID*: The group ID for your project is the Organization ID of your Anypoint Platform Organization. This field is required.
* *Artifact ID*: The artifact ID is the name of your project without a version. By default, Studio uses the artifact ID configured in your pom.xml file. This field is required.
* *Version*: The version of the asset you are publishing. This field is required.
. Select a project type. +
If you are publishing a new version of an already published asset, you cannot change the project type.
. Select the *Save updated project information to the pom.xml*  if you want to update your pom.xml file with the data you just provided. +
This option option updates your local project's information with the data configured in the `Publish to Exchange` window. If you do not select this option, the project is deployed with the configured data, but your local project information is not updated.
. Select *Finish*. +

You can follow the deployment progress in the Console View.
Once started, you cannot cancel the your asset's publication Exchange.


== See Also

* xref:set-credentials-in-studio-to.adoc[Configuring Anypoint Platform Credentials]
