= Publishing a Project to Exchange
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio allows you to connect to Exchange to publish your project as a new asset.

. Right-click your project folder in your Package Explorer view.
. Select *Anypoint Platform* > *Publish to Exchange*.
. Either select your Anypoint Platform user and business group or create a new Anypoint Platform account by clicking *Add Account*. +
Additionally you can click the "Add Account" button to use a new Anypoint Platform account.
. Verify that the required identification and version information for your project is present and correct:
* *Group ID* +
The group ID for your project is the organization ID of your Anypoint Platform organization.
* *Artifact ID* +
The artifact ID is the name of your project, minus its version. By default, Studio uses the artifact ID configured in your `pom.xml` file. 
* *Version*: The version of the asset you are publishing.
. Select a project type. +
If you are publishing a new version of an already published asset, you cannot change the project type.
. Select *Save updated project information to the pom.xml*  if you want to update your `pom.xml` file with the data you just provided. +
This option updates your local project information with the data configured in the *Publish to Exchange* window. If you do not select this option, the project is deployed with the configured data, but your local project information is not updated.
. Select *Finish*. +

You can follow deployment progress in the *Console* view.
Once started, you cannot cancel the your asset's publication Exchange.


== See Also

* xref:set-credentials-in-studio-to.adoc[Configuring Anypoint Platform Credentials]
