= Configuring your JDK Installation
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: jdk-requirement-lnx-worflow.adoc, jdk-requirement-wx-workflow.adoc, jdk-requirement-xos-worflow.adoc, studio-configure-vm-task-lnx.adoc, studio-configure-vm-task-unx.adoc, studio-configure-vm-task-wx.adoc

Anypoint Studio requires Java 8 to run properly.

To verify that you have the correct JDK version installed, type `java -version` in your command line.

* If you get the error `java: Command not found`, install the JDK 1.8.
* If you get a version different than 1.8, make sure to upgrade, or downgrade to 1.8.

After downloading and installing the JDK, make sure that your JDK installation is properly configured within the the `JAVA_HOME` environment variable by following the instructions below.

== Windows

. In Search, search for `System (Control Panel)` and select it.
. Click *Advanced System Settings*.
. Click *Environment Variables*.
. In *System Variables*, select the `PATH` environment variable.
. Click *Edit*.
+
If the `PATH` environment variable does not exist, click *New*.
. In *Edit System Variable* (or *New System Variable*), make sure that the JDK 1.8.0 `/bin` directory is the first item in your `PATH` environment variable, and click *OK*.
+
[NOTE]
--
Blank spaces are not allowed when defining a path on Windows.
--
+
. Click *OK*.

To verify that your installation was configured correctly, reopen the command prompt window, and type:

[source,console,linenums]
----
> java -version
----

This should print the version of the java tool.

== OSx

. Edit the startup file `~/.bashrc`.
. Modify `PATH` variable. +
Make sure that the JDK 1.8.0 `/bin` directory is the first item in your `PATH` environment variable, as shown below:
+
[source,console,linenums]
----
PATH=/usr/local/jdk1.8.0/bin:$PATH
export PATH
----
. Save and close the file.
. Load the startup file.
+
[source,console,linenums]
----
> source ~/.bashrc
----

To verify that your installation was configured correctly, type:

[source,console,linenums]
----
> java -version
----

This should print the version of the java tool.

== Linux

. Edit the startup file `~/.bashrc`.
. Modify `PATH` variable. +
Make sure that the JDK 1.8.0 `/bin` directory is the first item in your PATH environment variable, as shown below:
+
[source,console,linenums]
----
PATH=/usr/local/jdk1.8.0/bin:$PATH
export PATH
----
. Save and close the file.
. Load the startup file.
+
[source,console,linenums]
----
> . /.profile
----

To verify that your installation was configured correctly, type:

[source,console,linenums]
----
> java -version
----

This should print the version of the java tool.


== See Also

* xref:faq-default-browser-config.adoc[Troubleshooting Issues with Your Default OS Browser]
* xref:to-download-and-install-studio.adoc[Downloading and Installing Studio]
