= About Anypoint Studio JDK Requirement
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio 6.4.4 requires Java 7 or Java 8 depending on which Mule runtime you want to use:

* Mule 3.9.x requires Studio running on Java 8.
* Mule 3.5.x requires Studio running on Java 7.
* Other supported runtime versions work fine with both Java 7 or 8.

To verify that you have the correct JDK version installed, type `java -version` in your command line. +
If you get the error `java: Command not found`, install the JDK you need based on the runtime you want to use. +
If you get a version different than the one you want, make sure to upgrade, or downgrade to that version.

After downloading and installing the JDK, make sure that your JDK installation is properly configured within the the JAVA_HOME environment variable by following the instructions below:

* xref:jdk-requirement-wx-workflow.adoc[To Configure Java JDK (Windows)]
* xref:jdk-requirement-lnx-worflow.adoc[To Configure Java JDK (Linux)]
* xref:jdk-requirement-xos-worflow.adoc[To Configure Java JDK (Mac OSx)]

Under certain circumstances, if you had a JRE installation previous to installing the JDK, your default VM could still be configured as the JRE. +
To correct this, follow the instructions below to configure Anypoint Studio to point to your JDK installation as the default VM:

* xref:studio-configure-vm-task-wx.adoc[To Configure Studio's Default VM (Windows)]
* xref:studio-configure-vm-task-unx.adoc[To Configure Studio's Default VM (Mac OSx)]
* xref:studio-configure-vm-task-lnx.adoc[To Configure Studio's Default VM (Linux)]

If after doing so, Anypoint Studio still does not recognize your JDK installation, consider uninstalling your the JRE.


== See Also

* For more information about this configuration, check the https://docs.oracle.com/javase/8/docs/technotes/guides/install/install_overview.html#CJAGAACB[Oracle Documentation resource].