= Hardware and Software Requirements
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, requirements, os, jdk, installation, jre

This page lists the hardware, operating systems, Java, and other requirements for running MuleSoft products.


== Anypoint Studio

See xref:release-notes::studio/anypoint-studio.adoc[Anypoint Studio Release Notes] for the latest software changes.

[%header%autowidth.spread]
|===
2+|*Hardware Requirements:*
|
a|* 4GB of free memory available
* 2GHz CPU
* 10GB free hard drive space
2+|*Software Requirements:*
|*Java Environments*
a|
* Oracle JDK 1.8
* Oracle JDK 1.7.0 (recommended: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#jdk-7u80-oth-JPR[JDK 1.7.0_79/80]) - *Note*: If you install Anypoint Studio on a new MacOS computer, you also need to install https://support.apple.com/kb/DL1572[JRE 1.6]

|*Operating Systems*

a|June 2015 and newer:

* macOS 10.10.0 through 10.15.7 +
Studio is not compatible with macOS 11.x.
* Windows (32- and 64-bit) Windows 7, Windows 8, Windows 10
* RHEL 7.0
* Ubuntu Desktop 16.04
|===

NOTE: With Windows 32 bit with 4 GB RAM (maximum allowed by the OS) there is some times not enough memory when running other applications.


== Anypoint Studio as Eclipse Plug-in

[%header%autowidth.spread]
|===
2+|*Hardware Requirements:*
|
a|* 3GB of RAM
* 2GHz CPU
* 4GB free hard drive space

2+|*Software Requirements:*

|*Eclipse*

a|* Eclipse 4.4.2 for Java Developers or Java EE Developers
* Spring Tool Suite (STS) versions that run on top of Eclipse 4.4.2

|*Java Runtime Environments*

a|* Studio June 2015 and newer: Oracle JDK 1.7 or Oracle JDK 1.8

* Studio March 2015: Oracle JDK 1.7

|*Operating Systems*

a|* Windows (32- or 64-bit) Windows 7, Windows 8
* Mac OS (32- or 64-bit)
* Linux (32- or 64-bit)
|===

Get more information about installing xref:studio-in-eclipse.adoc[Studio as an Eclipse plug-in].