= Configure Hyperforce in Anypoint Studio

//This intro can be a partial so that all docs have the same intro. Let's consider that users don't read Hyperforce docs but products docs. In this case, for example, Studio docs.

Salesforce Hyperforce (Hyperforce) is a modern, scalable, and secure infrastructure designed to support your MuleSoft application deployments. Hyperforce enables you to deliver Mule apps rapidly and reliably to locations worldwide, giving you more choice and control over data residency. 

Currently, you can deploy to the following Hyperforce supported regions:
[%header%autowidth.spread,cols="a,a,a,a"]
|===
| Location | Control Plane  | Anypoint Platform URL
| North America | Canada Cloud  | `+ca1.platform.mulesoft.com+`
| APAC | Japan Cloud  | `+jp1.platform.mulesoft.com+`
|===

To deploy Mule apps via Anypoint Studio to any of these regions, you must configure these Anypoint Platform control plane URLs in the Anypoint Studio UI.

== Before You Begin

Before deploying Mule apps to Hyperforce your MuleSoft account must have access to a Hyperforce instance. Contact your MuleSoft account representative to provision a MuleSoft license to a Hyperforce instance.

== Hyperforce Supported Regions

Hyperforce is available in these regions:

[%header%autowidth.spread,cols="a,a,a,a"]
|===
| Location | Control Plane | Region | Anypoint Platform URL
| North America | Canada Cloud | ca-central-1 | ca1.platform.mulesoft.com
| APAC | Japan Cloud | ap-northeast-1 | jp1.platform.mulesoft.com
|===
//This intro can be a partial so that all docs have the same intro. Let's consider that users don't read Hyperforce docs but products docs. In this case, for example, Studio docs. 

== Configure Hyperforce Control Planes in Anypoint Studio

. Go to *Anypoint Studio* > *Settings* > *Anypoint Studio* > *Anypoint Platform*.
. Under *Control Plane Settings*,  select *Use this control plane* .
. In *Control Plane URL*, write the Anypoint Platform URL of the region to which your Mule app is deployed:
* Canada Cloud: `+ca1.platform.mulesoft.com+`
* Japan Cloud: `+jp1.platform.mulesoft.com+`
. Click *Apply and Close*.

[NOTE]
Use the *Select your region* options in the *Region Settings* to deploy your Mule application to US, EU, or GOV clouds.

== See Also
* xref:hyperforce::index.adoc[]
