= Import an API Specification from Design Center
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio enables you to import a RAML API specification from Design Center into either a new Mule project or an existing one.

This task only works for RAML types of API specifications.

== Import an API Specification from Design Center Into a New Project

. In the taskbar at the top of the Anypoint Studio display, select *File* > *New* > *Mule Project*.
. Type a name for your project.
. Select a Mule runtime engine version 4.1.4 or later.
. In the *API Specification* section, select the *Download RAML from Design Center* tab.
. In the *Location* field, click the *...* button and select *Design Center...*.
. Select your Anypoint Platform username. +
If you are not logged in, you can click the *Add Account* button to add your Anypoint Platform account.
. In the *Browse Design Center for APIs* window, select the Anypoint Platform business group where the API specification is located. +
If you have configured your AnyPoint Platform credentials, the username and business group options are unavailable. +
If you want to use a different account, click the *Add Account* button and log in again.
. From the list of available APIs, select the one you want and click *OK*.
. Click *Finish*.

Studio scaffolds your API specification. If you choose not to create flows out of your API specification, unselect the *Scaffold Flows From These API Specifications* checkbox.

== Import an API Specification from Design Center into an Existing Project

Importing an API specification from Design Center into an existing project deletes all your resources from your `src/main/resources/api` directory.

. In the Package Explorer view, right-click on your project and select *Anypoint Platform* > *Download RAML from Design Center*.
. Select your Anypoint Platform username. +
If you are not logged in, you can click the *Add Account* button to add your Anypoint Platform account.
. In the *Browse Design Center for APIs* window, select the Anypoint Platform business group where the API specification is located. +
If you have configured your AnyPoint Platform credentials, the username and business group options are unavailable. +
If you want to use a different account, click the *Add Account* button and log in again.
. From the list of available APIs, select the one you want and click *OK*.
. Click *Finish*.

Studio scaffolds your API specification. If you choose not to create flows out of your API specification, unselect the *Scaffold Flows From These API Specifications* checkbox.

== See Also

* xref:api-development-studio.adoc[API Development in Studio]
* xref:set-credentials-in-studio-to.adoc[Configure Anypoint Platform Credentials]