= Import an API Spec
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Import and implement an API spec into either a new Mule project or an existing one in Studio xref:import-api-specification-exchange.adoc[from Exchange] or xref:import-api-specification-maven.adoc[Maven].

Studio supports the following API specs:

* AsyncAPI 2.6
* OpenAPI Specification (OAS) 2.0 and 3.0 
* RESTful API Modeling Language (RAML)

After importing and implementing it, the API spec becomes part of your project as a dependency.

If you choose to implement your API specification as standalone attachment to your project, you can import a RAML specification from either xref:import-api-specification-local-file.adoc[your local hard drive] or from xref:import-api-specification-design-center.adoc[Anypoint Design Center].

See xref:api-development-studio.adoc[API development in Studio] for more information about these two different approaches.

== See Also

* xref:import-api-specification-exchange.adoc[Import an API spec from Exchange]
* xref:import-api-specification-maven.adoc[Import an API spec from Maven]
* xref:import-api-specification-local-file.adoc[Import an API spec from your local hard drive]
* xref:import-api-specification-design-center.adoc[Import an API spec from Anypoint Design Center]

