= Import and Implement an API Specification from MuleSoft VCS
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Import a RAML API specification from MuleSoft VCS into either a new Mule project or an existing one.

== Import and Implement an API Specification from MuleSoft VCS Into a New Project

. In the taskbar, select *File* > *New* > *Mule Project*.
. Type a name for your project.
. Select a Mule runtime engine version 4.1.4 or later.
. In the *API Specification* section, select the *Download RAML from MuleSoft VCS* tab.
. In the *Location* field, click *...* and select *MuleSoft VCS*.
. Select your Anypoint Platform username. +
If you're not logged in, click *Add Account* to add your Anypoint Platform account.
. In the *Browse MuleSoft VCS for APIs* window, select the Anypoint Platform business group where the API specification is located.
+
If you configure your Anypoint Platform credentials, the username and business group options are unavailable.
+
If you want to use a different account, click *Add Account* and log in again.
. Select an API from the list of available APIs and click *OK*.
. Click *Finish*.

Studio scaffolds your API specification. If you choose not to create flows out of your API specification, deselect *Scaffold Flows From These API Specifications*.

== Import and Implement an API Specification from MuleSoft VCS into an Existing Project

Importing an API specification from MuleSoft VCS into an existing project deletes all your resources from your `src/main/resources/api` directory.

. In the Package Explorer view, right-click on your project and select *Anypoint Platform* > *Download RAML from MuleSoft VCS*.
. Select your Anypoint Platform username.
+
If you're not logged in, click *Add Account* to add your Anypoint Platform account.
. In the *Browse MuleSoft VCS for APIs* window, select the Anypoint Platform business group where the API specification is located.
+
If you configure your Anypoint Platform credentials, the username and business group options are unavailable.
+
If you want to use a different account, click *Add Account* and log in again.
. Select an API from the list of available APIs and click *OK*.
. Click *Finish*.

Studio scaffolds your API specification. If you choose not to create flows out of your API specification, deselect *Scaffold Flows From These API Specifications*.

== See Also

* xref:api-development-studio.adoc[API Development in Studio]
* xref:set-credentials-in-studio-to.adoc[Configure Anypoint Platform Credentials]
