= Import and Implement an API Spec
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Import and implement an API spec into either a new Mule project or an existing one in Studio from Exchange, Maven, your local drive, or Design Center.

Studio supports the following API specs:

[%header%autowidth.spread,cols="a,a,a"]
|===
| API Spec | Version | More Information

| AsyncAPI 
| 2.6 
| 

* xref:import-api-specification-design-center.adoc[]**
* xref:import-api-specification-exchange.adoc[]**

[NOTE]
See xref:design-center::design-async-api.adoc[] in Design Center for more information about designing even-driven APIs using AsyncAPI in API Designer.

| OpenAPI Specification (OAS) 
| 2.0 and 3.0 
| 

* xref:import-api-specification-exchange.adoc[]**
* xref:import-api-specification-maven.adoc[]**

| RESTful API Modeling Language (RAML) 
| 0.8 and 1.0
| 

* xref:import-api-specification-design-center.adoc[]**
* xref:import-api-specification-exchange.adoc[]**
* xref:import-api-specification-local-file.adoc[]*
* xref:import-api-specification-maven.adoc[]*

|===

+++*+++ After importing and implementing the API spec, it's part of your project as a standalone attachment.

+++**+++ After importing and implementing the API spec, it's part of your project as a dependency.

See xref:api-development-studio.adoc[API development in Studio] for more information about these two different approaches.

== See Also

* xref:import-api-specification-exchange.adoc[]
* xref:import-api-specification-maven.adoc[]
* xref:import-api-specification-local-file.adoc[]
* xref:import-api-specification-design-center.adoc[]

