= API Lifecycle Development in Studio 7.4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To ensure that your Mule applications always refer to a single source of truth for your API specifications, MuleSoft introduces a workflow to design, publish, and implement your API specifications.

This workflow also lets you use both RAML and OAS specifications:

. Design an API specification in Design Center. +
You can either xref:design-center::design-create-publish-api-visual-editor.adoc[Create and Publish an API Specification with the Visual Editor] or xref:design-center::design-create-publish-api-raml-editor.adoc[Create and Publish an API Specification with the Code Editor].
. Publish that API specification to Exchange. +
Make your newly designed API available to your entire organization as an Exchange dependency.
. Import the API specification from Exchange to Studio. +
You API specification is imported to Studio as a dependency. Your Mule project now holds a pointer to the specific API version that you are implementing. Studio keeps track of newer versions of your API being published and notifies you when there is a new version available. +
See xref:api-sync.adoc[API Sync] for more information.

== Using Exchange as a Single Source of Truth For All Your Dependencies

This workflow lets you handle the APIs of your Mule application the same way you would handle the modules that compose your application. By leveraging Exchange as your unified repository for all the dependencies of your Mule application, you can keep up to date with the latest versions of your dependencies, ensuring that your application is up-to-date with the latest API requirements.

=== Local Copies vs Exchange Pointers

In previous versions of Studio, you could import an API specification from your local hard drive, or directly from Design Center into the `/src/main/api/` directory in the structure your project. This local copy of your API works as a standalone attachment of your project, without chances of ever align with other products where the same specification might be being worked on. For example, whenever the API that you imported from Design Center was updated outside your Studio environment, you needed to re-import the API into your project, and re-generate all the flows based on the updated specification.

Because the implementation of your API may change on each iteration, it's important for you to keep track of the changes so your Mule application can be updated to match newer specifications. To help you keep track of these changes, you must treat your API specifications as dependencies of your project. This way, on each change of the specification's design, the API publishes a new API version that you can manage from Studio, and update your application to match the new API version. Each API version that you import from Exchange is not stored as a local copy on your project's structure, but as a pointer to the API version dependency in Exchange. By referencing the API version in Exchange, Studio can periodically check the status of the version and lets you know when a new version is available.

When you have API specifications as references pointing to Exchange, you can choose leverage the latest supported OAS specification design in Design Center and Exchange, to publish your OAS specification, import it to Studio, and automatically scaffold the flows for it.

== Scaffold RAML and OAS Specifications

You can choose to design your API using either RAML or OAS specifications. When you import these specifications as dependencies of your flows, you can choose to automatically generate the flows (scaffold) in your canvas based on the endpoints described in the API specification.

Studio leverages APIkit to scaffold the flow and make it easier for you to start developing a Mule application out of an API specification.

By default, APIkit tries to parse your API specification using AMF parser to support scaffolding for OAS specifications. If this fails, APIkit defaults the the regular Java parser to parse RAML specifications.

See xref:/[OAS Support in Studio]






