= To Configure Proxy Settings (Anypoint Studio)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio allows you to configure proxy configurations for when your computer is behind a proxy server and needs to connect to the internet to download plugins and install updates.

Anypoint Studio supports configurations for authenticated and non-authenticated proxies.

. Open the preferences view in the manner appropriate to your OS: +
* In MacOS, either navigate to *Anypoint Studio* > *Preferences...* or press `cmd + ,`.
* In Windows and Linux, navigate to *Window* > *Preferences...*.
. Under *General* select *Network Connections*.
. Select your Active Provider: +
* *Direct* causes Anypoint Studio to open connections without the use of a proxy server.
* *Manual* causes Anypoint Studio to open connections using the settings defined in the options below.
* *Native* causes Anypoint Studio to open connections using settings discovered in the OS where you installed Anypoint Studio.
. Click *Edit* when selecting the proxy entry for each schema to configure its host and port number.
+
If you're using an authenticated proxy, select *Requires Authentication* and complete the *User* and *Password* fields.
. If necessary, you can add bypasses to your proxy. This is a list of hosts that should not use any proxy.
+
Click *Add Host...* to add hostnames to your proxy bypass list.
+
Keep in mind that when setting a manual provider, don't disable the default `localhost` and `127.0.0.1` bypasses. If you disable the bypasses, the embedded Mule runtime within Studio won't be able to reach your application.

When applying changes to your proxy settings, Anypoint Studio restarts the Mule instance used to obtain metadata and test outbound connections.
If this fails, manually restart your instance: navigate to *Preferences* > *Tooling*, and click *Restart Instance*.

== See Also

* xref:proxy-settings-reference.adoc[Proxy Settings Reference (Anypoint Studio)]
