= Setting up your Development Environment
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Setting up a proper environment from the beginning is crucial for success with using Mule. The following document outlines the steps to be taken before any significant use of Anypoint Studio, Mule ESB, and our Cloud Solutions.

== Anypoint Studio Setup

=== Check Hardware and Software Requirements

* Click xref:3.7@mule-runtime::hardware-and-software-requirements.adoc[here] to find information regarding the Hardware and Software requirements. Please correctly align with the appropriate Hardware and Software before proceeding.

=== Install Oracle JDK

* If operating Mule 3.7, download and install the newest version of Oracle JDK http://www.oracle.com/technetwork/java/javase/downloads/index.html[here].
For Mule 3.6 and below, please note Java 7 is compatible.

=== Download Anypoint Studio

Download Anypoint Studio https://www.mulesoft.com/platform/studio[here].

=== Setup and Learn about Maven

Maven is a powerful build automation tool used for software project management. We highly urge our customers to use Maven, Gradle, or a similar in-house tool with any significant usage of MuleSoft software.

* Learn more about Maven http://maven.apache.org/guides/getting-started/[here].

* Start learning how to use Maven with Mule xref:maven-support-in-anypoint-studio.adoc[here].

=== Set Up Code Repository

Code Repositories facilitate the tracking and versioning of changes developers make to a software project; this enables several people to work on the same project simultaneously without creating conflicts among the changes and additions they make.

* Learn more about two recommended Code Repositories: http://subversion.apache.org/[Subversion] and http://git-scm.com/[Git].

* Start learning how to use Subversion with Studio xref:using-subversion-with-studio.adoc[here].

=== Set Up a Maven Repository Manager

A repository manager is a dedicated server application designed to manage repositories (internal and third party) of binary components. The usage of a repository manager is a best practice for any significant usage of Maven.

* Learn more about two recommended tools here: http://www.sonatype.org/nexus/downloads/[Nexus] and http://www.jfrog.com/open-source/[Artifactory].

=== Obtain credentials to access paid components and controls

Please Note this only has to be done once. The project manager or who ever is responsible for project oversight should complete this step as well as step 1.8.

* Login to the Support portal https://help.mulesoft.com[here]. If you do not have credentials to login, please contact your Customer Success Manager.

* Click the "Case" tab located on the top of the Support Portal Home page.

* Click the "Create New Case" button, at the right of the page header

* Fill out the required information (highlighted in red) and in the "Description" field please include a request for your credentials.

=== Configure MuleSoft Repositories

* Open Nexus. If you do not have Nexus learn more about Nexus http://www.sonatype.org/nexus/downloads/[here]. If you are using a different Repository Manager tool, please contact your Customer Success Manager.

* Log in as administrator, open the Repositories tab, select *Add…->Proxy Repository*.

* Create a new proxy repository with the following configuration:

** Repository ID: muleee

** Repository Name: MuleSoft EE Repository

** Set up Remote Storage Location. Click https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/[here].

** Check the Authentication checkbox

** Fill in User Name (User Name obtained from Support) and password.

== On Premises

=== Check system compatibility with platform software.

* Please review the platform software compatible with Mule ESB xref:3.7@mule-runtime::hardware-and-software-requirements.adoc[Hardware and Software Requirements].

=== Install ESB

* Click xref:3.7@mule-runtime::downloading-and-starting-mule-esb.adoc[here] for detailed steps on installing ESB on premises.

=== Download your license key file

* Login to the Support portal https://help.mulesoft.com[here]. If you do not have credentials to login, please contact your Customer Success Manager.

* Click the "Subscriptions" tab located on the top of the Support Portal Home page.

* Click on the "Subscription Name" of the Subscription you would like a license key for. Please note that you must click on the "Subscription Name" (second column on the right) or you will not be forwarded to the correct page.

* Click on the "License ID" number found on the bottom left of the page.

* Click on the "View" button to download your license key.

=== Install License Key

* Click xref:3.7@mule-runtime::installing-an-enterprise-license.adoc[here] to learn how to install your license key.

=== Setup the Runtime Manager

You can manage both your applications that are deployed to the cloud and on premises through the Cloud version of the Runtime Manager, found in the https://anypoint.mulesoft.com[Anypoint Platform]. For more information on configuring the Runtime Manager on the cloud, please see the xref:runtime-manager::managing-servers.adoc[Managing Servers] topic.

[TIP]
If your organization's security policies require that you carry out everything on premises, you can instead install the Anypoint Platform into a local server and run it from there. If you’re interested in requesting the Anypoint Platform Private Cloud Edition, please contact your sales representative.

== Anypoint Platform/Cloud

=== Get Admin credentials for Anypoint Platform

* If you do not already have Anypoint Platform credentials, email you Customer Success Manager. He/she will set it up up, and email you with your credentials.

=== Create Business Groups on the Anypoint Platform.

* Click https://anypoint.mulesoft.com/#/signin[here] to login into the support portal and create a business group.

=== Add people to the appropriate Business Groups and provision access accordingly.

* Click https://anypoint.mulesoft.com/#/signin[here] to login into the support portal and add people to business groups.

=== Create Different Environments on Anypoint Platform

* Click https://anypoint.mulesoft.com/#/signin[here] to login into the support portal and create different environments.

=== Set Up the Runtime Manager

* It is ready to use! Click xref:runtime-manager::index.adoc[here] to learn how to begin using the Runtime Manager!

=== Use the Platform

* Now that you have an account and are all set up, you are ready to create, build, run, manage, and enhance the experience of using your APIs and cloud based integrations through the platform.

== Frequently Asked Questions

=== Does Studio Require any license keys?

No. Studio does not require any customer specific license keys. Just download Studio https://www.mulesoft.com/platform/studio[here] and start learning how to use it xref:index.adoc[here].

=== How many additional users can I add to an account?

Each account is different. Depending on the Customer's Use Case and their needs we provide access to varying numbers of users. Please contact your Customer Success Manager for inquires with regards to the number of users you can add to your account.

=== How do I access the Support Portal?

Login to the Support portal https://help.mulesoft.com[here]. If you do not have credentials to login, please contact your Customer Success Manager.

=== How do I file a support ticket within the Support Portal?

. Login to the Support portal https://help.mulesoft.com[here]. If you do not have credentials to login, please contact your Customer Success Manager.

. Click the "Case" tab located on the top of the Support Portal Home page.

. Click the "Create New Case" button, at the right of the page header.

. Fill out the required information (marked by an asterisk(*)). Our support team will respond soon.

=== Do you need to configure servers with Anypoint Studio?

No, Anypoint Studio runs as an independent application on your machine and it does not need to be configured with any servers.

=== Where do I find my license key?

. Login to the Support portal https://help.mulesoft.com[here]. If you do not have credentials to login, please contact your Customer Success Manager.

. Click the "Subscriptions" tab located on the top of the Support Portal Home page.

. Click on the "Subscription Name" of the Subscription you would like a license key for. Please note that you must click on the "Subscription Name" (second column on the right) or you will not be forwarded to the correct page.

. Click on the "License ID" number found on the bottom left of the page.

. Click on the "View" button to download your license key.

=== What happens when my license key expires?

MuleSoft operates an annual subscription model. Every year in order to continue to utilize MuleSoft, you will need to renew your account. Your Customer Success Manager will reach out with regards to renewal during their regular cadence with you. However, if you are ever interested in discussing renewal beforehand, please do not hesitate to reach out to your Customer Success Manager.
