= Configuring XULRunner as Studio’s Default Layout Engine (MacOS)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

. Download `XULRunner` (we recommend http://ftp.mozilla.org/pub/xulrunner/releases/24.0/runtimes/[v24.0]).
. Unzip your package and install it.
. Go to your `/Applications` folder, right click the AnypointStudio.app package and select `Show Package Contents`.
. Navigate to `Contents > Eclipse` and open your AnypointStudio.ini file.
. Add a `-Dorg.eclipse.swt.browser.XULRunnerPath=` variable with the full path to your XULRunner binaries:
+
----
-Dorg.eclipse.swt.browser.XULRunnerPath={YourXULRunnerFolder}
----
+
[TIP]
XULRunner binaries are located in a subfolder within the directory where you extracted the XULRunner package: `XUL.framework/Versions/Current/`


== See Also

* xref:studio-xulrunner-wx-task.adoc[Configuring XULRunner as Studio's Default Layout Engine (Windows)]
* xref:studio-xulrunner-lnx-task.adoc[Configuring XULRunner as Studio's Default Layout Engine (Linux)]