= To Configure Studio's Default VM (Windows)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To configure the default VM for Anypoint Studio:

. Locate your `AnypointStudio.ini` file:
+
This file is located within your Anypoint Studio's installation directory.
. Add the -vm option to point to your specific JDK installation path.
+
[source,text,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\bin\javaw.exe
----
+
[NOTE]
--
Blank spaces are not allowed when defining paths on Windows. This is why `\Program Files\` changes to `\progra~1\`.
--
+
If you encounter “Java was started but returned exit code=1” error while starting Anypoint Studio, modify the -vm argument to point to the jvm.dll as follows:
+
[source,text,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\jre\bin\server\jvm.dll
----

When configuring the -vm option, its format must be exact:

* The -vm option and the installation path must be in separate lines.
* The value must be the full absolute or relative path to the Java executable, not just to the Java home directory.
* The -vm option must occur after the other Studio-specific options (such as -product, --launcher.*, etc), but before the -vmargs option, since everything after -vmargs is passed directly to the JVM.

== See Also

* xref:jdk-requirement-wx-workflow.adoc[To Configure Java JDK (Windows)]