= To Configure Studio's Default VM (Mac OSx)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To configure the default VM for Anypoint Studio:

. Locate your `AnypointStudio.ini` file by right clicking on the Anypoint Studio icon and selecting show package contents in the menu.
+
This file is located in `Applications/AnypointStudio`.
. Add the -vm option to point to your specific JDK installation path. If you have multiple JDKs installed type 'java /usr/libexec/java_home -verbose' to see the full path to your JDKs.
+
[source,text,linenums]
----
-vm
/usr/bin
----

When configuring the -vm option, its format must be exact:

* The -vm option and the installation path must be in separate lines.
* The value must be the full absolute or relative path to the Java executable, not just to the Java home directory.
* The -vm option must occur after the other Studio-specific options (such as -product, --launcher.*, etc), but before the -vmargs option, since everything after -vmargs is passed directly to the JVM.

== See Also

* xref:jdk-requirement-xos-worflow.adoc[To Configure Java JDK (Mac OSx)]
