= Anypoint Studio Update Sites
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, esb, studio, anypoint studio, update sites, updates, extensions, plug-ins, plugins, download

Update sites in Anypoint Studio are used to update or install Studio, the embedded Mule runtime, connectors or other useful development tools.

== Accessing an Update Site

. Go to *Help* > *Install New Software*.
. Select one of these update sites from the drop-down menu next to the *Work with* field.

=== Adding Additional Update Sites

If one of the update sites listed below does not show up in your Anypoint Studio installation, you can add it manually:

. Go to *Help* > *Install New Software*.
. Click the *Add...* button next to the work-with drop-down menu.
. Type a Name to identify the update site and, in Location type the URL of the update site.
. Click OK

// *Note*: None of the URLs listed below are accessible from a web browser. Only use them in the Anypoint Studio *Work with* field.

[TIP]
Verify your Studio version before proceeding, as installing updates from the incorrect update sites can cause errors. +
To check your version of Anypoint Studio, go to *Anypoint Studio* > *About Anypoint Studio*.

== Studio Update Site

Updates for Anypoint Studio application and components, Mule runtime, SAP connector and RAML editor.

`+http://studio.mulesoft.org/s3/updates+`

Updates:

* DataWeave.
* Mule runtime 4.1.n EE.

== Mule Runtimes for Anypoint Studio Update Site

Updates the Mule runtime version embedded within Studio.

`+http://studio.mulesoft.org/s3/studio-runtimes/+`

Updates:

*  Mule Server Runtime 4.x.x EE.

// == Patches for Anypoint Studio Update Site
//
// Contains all the patch versions for a given Studio version.
//
// `+http://studio.mulesoft.org/s2/patches/+`

== RAML Editor Update Site

Updates the RAML Editor in Anypoint Studio.

`+http://studio.mulesoft.org.s3.amazonaws.com/s2/ramleditor/+`

== MUnit Update Site

xref:2.1@munit::index.adoc[MUnit] framework for testing Mule Applications

`+http://studio.mulesoft.org/s3/munit+`


== Allowing Connection to Update Site Through Firewall

If you are on a network with firewall restrictions, you may find that the Studio update sites are blocked and you are unable to download extensions. Configure your firewall so that it allows the following sites, which permits Studio to connect to the above update sites:

Allow on Firewall:

* `+http://studio.mulesoft.org/+`

* `+http://repository.mulesoft.org/connectors/releases/+`

* `+http://download.eclipse.org/technology/m2e/releases+`

* `+http://download.eclipse.org/eclipse/updates+`

* `+http://subclipse.tigris.org/+`

* `+http://findbugs.cs.umd.edu/eclipse/+`


== See Also

* xref:set-credentials-in-studio-to.adoc[Configuring Anypoint Platform Credentials]
* xref:add-modules-in-studio-to.adoc[Adding Modules to Your Project]
