= Updating Studio, Mule and Components
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, esb, studio, anypoint studio, update sites, updates, extensions, plug-ins, plugins, download

Update sites in Anypoint Studio are used to update or install Studio, Mule, connectors or other useful development tools. See how to access and find update sites from Studio.

[NOTE]
In order to install the latest runtime with Studio, you must access the *Anypoint Studio Update Site*.


== To Access an Update Site

To access an update site in Studio:

. Go to *Help* > *Install New Software*.
. Select one of these update sites from the drop-down menu next to the *Work with* field.
. If you don't see the site you need, click *Add* to add it manually.

*Note*: None of the URLs listed below are accessible from a web browser. Only use them in the Anypoint Studio *Work with* field.

[WARNING]
====
Verify your Studio version before proceeding, as installing updates from the incorrect update sites can cause errors.

To check your version of Anypoint Studio, go to *Anypoint Studio* > *About Anypoint Studio*.
====

== Anypoint Studio Update Site

Updates for Anypoint Studio application and components, Mule runtime, SAP connector and RAML editor.

`+http://studio.mulesoft.org/r5/updates+`

*Updates:*

* DataWeave and DataMapper
* SAP Connector
* Mule runtime 3.8.n EE. For previous versions see <<mule-versions,Mule Runtimes for Studio>>

[[mule-versions]]
== Mule Runtimes for Studio Update Site

Older Mule Runtime CE and EE versions

`+http://studio.mulesoft.org/r5/studio-runtimes/+`

== Anypoint Connectors Update Site

All Community, Standard, Select, and Premium Anypoint Connectors available for Studio installation. Connector names are appended with the minimal runtime they support.

`+http://repository.mulesoft.org/connectors/releases/3.5.0+`

== APIkit Update Site

`+http://studio.mulesoft.org/r5/apikit+`

*Provides:*

* APIkit Studio Plugin updates for pre-Mule 3.8.0 installations
* RAML API Editor updates

Read more about xref:apikit::index.adoc[APIkit].

== API Gateway Update Site

API Gateway runtime updates for pre-Mule 3.8.0 installations

`+http://studio.mulesoft.org/r5/api-gateway/+`

Mule 3.8.0 unifies the API Gateway runtime and APIkit with the core Mule runtime.

== Anypoint Enterprise Security Update Site

`+http://security-update-site-1.6.s3.amazonaws.com+`
Provides:

* Mule Security Module Extensions:
** CRC-32
** Encrypted Property Placeholder
** Encryption
** OAuth 2 Provider
** Security Filters
** Signature
* Anypoint Studio Properties File Editor

*Note*: You need an Enterprise license to run applications containing xref:3.8@mule-runtime::anypoint-enterprise-security.adoc[Anypoint Enterprise Security] features.

== Anypoint DevKit Update Site

Anypoint Connector DevKit Studio Module.


`+http://studio.mulesoft.org/r5/devkit+`

== Anypoint Studio Eclipse Plugin Update Site

Eclipse plugin version of Anypoint Studio
Read more about installing xref:studio-in-eclipse.adoc[Anypoint Studio as an Eclipse Plugin].

`+http://download.eclipse.org/eclipse/updates/4.4+`

== MUnit Update Site

xref:1.3@munit::index.adoc[MUnit] framework for testing Mule Applications

`+http://studio.mulesoft.org/r5/munit+`

== To Allow Connection to Update Site Through Firewall

[WARNING]
====
*Are you behind a firewall?*

If you are on a network with firewall restrictions, you may find that the Studio update sites are blocked and you are unable to download extensions. Configure your firewall so that it allows the following sites, which permits Studio to connect to the above update sites:

Allow on Firewall:

* `+http://studio.mulesoft.org/+`

* `+http://repository.mulesoft.org/connectors/releases/+`

* `+http://download.eclipse.org/technology/m2e/releases+`

* `+http://download.eclipse.org/eclipse/updates+`

* `+http://subclipse.tigris.org/+`

* `+http://findbugs.cs.umd.edu/eclipse/+`

====