= Studio in Eclipse
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: 6.5@studio::studio-in-eclipse.adoc
:keywords: mule, esb, anypoint studio, studio, eclipse plug-in

As an Eclipse-based IDE, Anypoint Studio has adopted many of the functionalities Eclipse has to offer. However, you don't need to download a new IDE in order to take advantages of all that Studio provides. If you are already an Eclipse user, you can simply download and install *Studio as an Eclipse plug-in*.

[NOTE]
====
The Anypoint Studio Eclipse plugin is accessible in the Java, Java EE, and STS distributions that use Eclipse 4.7.2.

*Note*: Anypoint Studio supports JDK 8 only.
====

. In Eclipse, under the *Help* menu, select *Install New Software.*
. In the first panel of the *Install* wizard, enter the following URL in the *Work With* field, then click *Next*.
+
`+http://studio.mulesoft.org/r6/plugin+`
+
. Click the checkbox for *Anypoint Studio* and click *Next.*
. Review the install details, then click *Next*.
. Accept the terms and conditions of the license agreement, then click *Finish*.
. Eclipse installs *Anypoint Studio*, then demands a restart of the application.
. After Eclipse restarts, click *Window* > *Open Perspective* > *Other* > *Mule Design*.  +

Keep in mind that it is not possible to install Anypoint Studio plugin for Studio versions 6.5 and 7.x in the same Eclipse installation. +

== Available Software in the Update Site

The Anypoint Studio Eclipse Plugin contains the following packages:

* *Anypoint Connectors*
** Amazon S3 Connector (Mule 3.5.0+)
** Amazon SQS Connector (Mule 3.5.0+)
** Anypoint MQ Connector (3.7+)
** CMIS Connector (Mule 3.5.0+)
** Magento Connector (Mule 3.5+)
** Mongo DB Connector (Mule 3.5+)
** Salesforce Connector (Mule 3.5+)
** Twitter Connector (Mule 3.5+)
* *Anypoint Studio*
** Anypoint Studio Core Components
** Anypoint Studio Thirdparty Components
** Mule Server Runtime 3.8.3 EE
** MuleSoft Enterprise Java Connector for SAP
* *APIkit*
** Anypoint APIkit SOAP Extension
** APIkit Studio Plugin
** APIkit Studio Plugin
** APIkit Studio Plugin
** RAML API Editor
* *MUnit*
** MUnit Anypoint Studio Plugin
** Munit Synchronize Module for Integration Testing
