= To Configure Studio's Default VM (Linux)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To configure the default VM for Anypoint Studio:

. Locate your `AnypointStudio.ini` file:
:: This file is located in `/usr/lib/anypointstudio/anypointstudio.ini`.
. Add the -vm option to point to your specific JDK installation path.
+
[NOTE]
--
The paths detailed below are examples for the JDK 1.8 paths. +
If you want to configure older JDKs as the default VM for Anypoint Studio, provide the installation path to the version you want to use.
--
+
[source,text,linenums]
----
-vm
/opt/sun-jdk-1.8.0.73/bin/java
----

When configuring the -vm option, its format must be exact:

* The -vm option and the installation path must be in separate lines.
* The value must be the full absolute or relative path to the Java executable, not just to the Java home directory.
* The -vm option must occur after the other Studio-specific options (such as -product, --launcher.*, etc), but before the -vmargs option, since everything after -vmargs is passed directly to the JVM.

== See Also

* xref:jdk-requirement-wx-workflow.adoc[To Configure Java JDK (Windows)]