= Synchronize API Specifications with Design Center
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Anypoint Studio 7.5 and later enables you to import a RAML or OAS API specification from Design Center into an API Project in Studio to edit it offline, and stage and push your changes as you would do with any version control system.

This feature only works when importing an API from Design Center as shown in the following process. +
To import an API specification to write a Mule application implementation see xref:import-api-specification-design-center.adoc[Import an API Specification From Design Center].

== Import an API Specification From Design Center To Edit Locally

. In the taskbar at the top of the Anypoint Studio display, select *File* > *Import*.
. Select *Anypoint Studio* > *API Specification from Design Center*.
. Select your Anypoint Platform username. +
If you are not logged in, you can click the *Add Account* button to add your Anypoint Platform account.
. In the *Browse Design Center for APIs* window, select the Anypoint Platform business group where the API specification is located. +
If you have configured your AnyPoint Platform credentials, the username and business group options are unavailable. +
If you want to use a different account, click the *Add Account* button and log in again.
. From the list of available APIs, select the one you want and click *Finish*.

Studio imports the API specification as an API project so that you can work on your API project offline.

=== Commit Changes to Your API Project

The VCS in Studio tracks every change you make to your project and shows them in the *Unstaged Changes* area of your *Git Staging* view.

* Use the *Add selected files to the index* icon to stage for commit the files that you selected.
* Use the *Add all files including not selected ones to the index* icon to stage for commit all unstaged changes.

When you staged all the changes that you want to commit, write a commit message in the *Commit Message* section and select *Commit* to add the commit to your local copy, or *Commit and Push* to also push the change to Design Center.

See xref:git-staging-view-reference.adoc[Git Staging View Reference] for more information about this view.


