= Download and Install Anypoint Studio (Windows)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: jdk-requirement-lnx-workflow.adoc, jdk-requirement-wx-workflow.adoc, jdk-requirement-xos-workflow.adoc, studio-configure-vm-task-lnx.adoc, studio-configure-vm-task-unx.adoc, studio-configure-vm-task-wx.adoc, faq-jdk-requirement.adoc

. Download the Anypoint Studio installation file from the https://www.mulesoft.com/lp/dl/studio[Download Site].
. Extract the Windows installation file into the `C:\` root folder.
+
[NOTE]
.To avoid installation errors:
====
* Ensure that you extract the installation file into the `C:\` folder so that the `AnypointStudio.exe` file is located in the `C:\AnypointStudio\` folder after installation.
* Ensure that your user has read and write permissions for the `C:\` directory.
* If you use a Windows antivirus application, ensure that the `plugins/` and `features/` directories are in the *trusted* category.
====
. Open the extracted Anypoint Studio.
+
When Studio first runs, the embedded OpenJDK Platform libraries might cause a Windows Security alert. +
Ensure to allow the OpenJDK Platform library from Temurin publisher through your Windows firewall.
. Click *OK* to accept the default workspace. +
** If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or later. +
Studio 7.x supports only Mule 4.x projects, because the structure of the project, export format, XML, and scripting language are different from the ones used by Mule 3.x.
