= Downloading and Installing Anypoint Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: to-download-and-install-studio-wx.adoc, to-download-and-install-studio-ox.adoc, to-download-and-install-studio-lx.adoc

== Prerequisites

* Make sure you have the Java SE JDK 8 installed and configured. +
See xref:faq-jdk-requirement.adoc[Configuring your JDK Installation] for instructions.
* Download the Anypoint Studio installation file from the https://www.mulesoft.com/lp/dl/studio[Anypoint Studio Download Site].

[NOTE]
Anypoint Studio 7.x only supports Mule 4.x projects since the structure of the project, export format, XML and scripting language are different.

[[windows]]
== Windows

. Extract the Windows installation file into the `C:\` root folder. +
If you are using a Windows Anti-Virus application, ensure that the `plugin/` and `features/` directories are under the “trusted” category.
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace.
+
include::partial$installation.adoc[tag=workspace-reuse]

. Locate your `AnypointStudio.ini` file. +
This file is located within your Anypoint Studio's installation directory.
. Add the -vm option to point to your specific JDK installation path.
+
[source,text,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\bin\javaw.exe
----
+
* Blank spaces are not allowed when defining paths on Windows. This is why `\Program Files\` changes to `\progra~1\`.
include::partial$installation.adoc[tag=vm-argument]
+
If you encounter “Java was started but returned exit code=1” error while starting Anypoint Studio, modify the -vm argument to point to the `jvm.dll` as follows:
+
[source,text,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\jre\bin\server\jvm.dll
----

[[osx]]
== OSx

. Extract the Anypoint Studio package and move it to your `/Applications` directory.
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace. +
include::partial$installation.adoc[tag=tilde-workspace-reuse-note]

. Go to your `/Applications` folder, right click the `AnypointStudio` package and select *Show Package Contents*.
. Go to to `Contents` > `Eclipse`, and open the `AnypointStudio.ini` file.
. Add the -vm option to point to your specific JDK installation path.
+
[source,text,linenums]
----
-vm
/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java
----
+
include::partial$installation.adoc[tag=vm-argument]

[[linux]]
== Linux

[NOTE]
To support some of Studio Themes in Linux, it is recommended to have GTK version 2 installed.

. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace. +
include::partial$installation.adoc[tag=tilde-workspace-reuse-note]

. Locate your `AnypointStudio.ini` file:
+
This file is located in `/usr/lib/anypointstudio/anypointstudio.ini`.
. Add the -vm option to point to your specific JDK installation path.
+
[source,text,linenums]
----
-vm
/opt/sun-jdk-1.8.0.73/bin/java
----
+
include::partial$installation.adoc[tag=vm-argument]
