= Downloading and Installing Anypoint Studio (Linux)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Prerequisites

* Ensure that you have the Java SE JDK 8 installed and configured.
* To support the Studio Theme in Linux, have GTK version 2 installed.
* Download the Anypoint Studio installation file from the https://www.mulesoft.com/lp/dl/studio[Download Site].


[NOTE]
Anypoint Studio 7.x supports only Mule 4.x projects, because the structure of the project, export format, XML, and scripting language are different than the ones used by Mule 3.x.


== Installation

. Open the extracted Anypoint Studio.
. Click *OK* to accept the default workspace.
** You must Use an absolute path when defining your workspace because Anypoint Studio does not expand the `~` tilde used in Unix and Linux systems.
** If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or later.


== Troubleshooting

If Anypoint Studio fails to load with a *An Error Has Occured* message, you must configure it to point to your JDK installation as the default VM:

. Locate your `AnypointStudio.ini` file in `/usr/lib/anypointstudio/anypointstudio.ini`.
. Add the `-vm` option to point to your specific JDK installation path.
+
[source,text,linenums]
----
-vm
/opt/sun-jdk-1.8.0.73/bin/java
----
+
* The `-vm` option and the installation path must be on separate lines.
* The value must be the full absolute or relative path to the Java executable, not just to the Java home directory.
* The `-vm` option must occur after the other Studio-specific options (such as `-product`, `--launcher.*`, etc), but before the `-vmargs` option.

== See Also

* xref:studio-xulrunner-lnx-task.adoc[Configuring XULRunner as Studio's Default Layout Engine (Linux)]
* xref:jdk-requirement-lnx-worflow.adoc[Configuring Java JDK (Linux)]
* xref:studio-configure-vm-task-lnx.adoc[Configuring Studio's Default VM (Linux)]
