= To Install Anypoint Studio 7.1 (Linux)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

To support some of Studio Themes in Linux, it is recommended to have GTK version 2 installed.

* Before downloading and launching Anypoint Studio, make sure you have the Java SE JDK 8 installed.

You can only download the latest version of Anypoint Studio. These instructions are covered only if you already have the corresponding ZIP file for an older version.

To install Anypoint Studio 7.1:

. Extract your Anypoint Studio 7.1 ZIP file.
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace. +
When setting a custom path to your workspace, keep in mind that Anypoint Studio does not expand the `~` tilde used in Unix/Linux systems. It is recommended to use the absolute path when defining your workspace.
+
[NOTE]
--
You cannot reuse a workspace used by Anypoint Studio 6.x or below. +
If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--

Anypoint Studio displays a welcome message when it loads for the first time. +
Click Get Started to start using Anypoint Studio.



== See Also

* xref:studio-xulrunner-lnx-task.adoc[To Configure XULRunner as Studio's Default Layout Engine (Linux)]
* xref:jdk-requirement-lnx-worflow.adoc[To Configure Java JDK (Linux)]
* xref:studio-configure-vm-task-lnx.adoc[To Configure Studio's Default VM (Linux)]