= Downloading and Installing Anypoint Studio (Windows)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: jdk-requirement-lnx-worflow.adoc, jdk-requirement-wx-workflow.adoc, jdk-requirement-xos-worflow.adoc, studio-configure-vm-task-lnx.adoc, studio-configure-vm-task-unx.adoc, studio-configure-vm-task-wx.adoc, faq-jdk-requirement.adoc

include::partial$installation.adoc[tag=prereq]

After downloading and installing the JDK, make sure that your JDK installation is properly configured within the the `JAVA_HOME` environment variable by following the instructions below.

. In Search, search for `System (Control Panel)` and select it.
. Click *Advanced System Settings*.
. Click *Environment Variables*.
. In *System Variables*, select the `PATH` environment variable.
. Click *Edit*.
+
If the `PATH` environment variable does not exist, click *New*.
. In *Edit System Variable* (or *New System Variable*), make sure that the JDK 1.8.0 `/bin` directory is the first item in your `PATH` environment variable, and click *OK*.
+
[NOTE]
--
Blank spaces are not allowed when defining a path on Windows.
--
+
. Click *OK*.



== Installation

. Extract the Windows installation file into the `C:\` root folder. +
If you are using a Windows Anti-Virus application, ensure that the `plugin/` and `features/` directories are under the “trusted” category.
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace.
+
include::partial$installation.adoc[tag=workspace-reuse]

. Locate your `AnypointStudio.ini` file. +
This file is located within your Anypoint Studio's installation directory.
. Add the -vm option to point to your specific JDK installation path.
+
[source,text,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\bin\javaw.exe
----
+
* Blank spaces are not allowed when defining paths on Windows. This is why `\Program Files\` changes to `\progra~1\`.
include::partial$installation.adoc[tag=vm-argument]
+
If you encounter “Java was started but returned exit code=1” error while starting Anypoint Studio, modify the -vm argument to point to the `jvm.dll` as follows:
+
[source,text,linenums]
----
-vm
C:\progra~1\Java\jdk1.8.0_73\jre\bin\server\jvm.dll
----

== See Also

* xref:studio-xulrunner-wx-task.adoc[Configuring XULRunner as Studio's Default Layout Engine (Windows)]
* xref:jdk-requirement-wx-workflow.adoc[Configuring Java JDK (Windows)]
* xref:studio-configure-vm-task-wx.adoc[Configuring Studio's Default VM (Windows)]
