= To Download and Install Anypoint Studio 7.2 (OSx)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

* Before downloading and launching Anypoint Studio, make sure you have the Java SE JDK 8 installed.

To install Anypoint Studio 7.2:

. Download Anypoint Studio from the https://www.mulesoft.com/lp/dl/studio[Anypoint Studio Download Site] and extract it.
If you are using OS version Sierra, it is important that you move your extracted app to the `/Applications` folder before you launch it.
. Open the extracted Anypoint Studio.
. Click *OK* to accept the default workspace. +
When setting a custom path to your workspace, keep in mind that Anypoint Studio does not expand the `~` tilde used in Unix/Linux systems. It is recommended to use the absolute path when defining your workspace.
+
[NOTE]
--
You cannot reuse a workspace used by Anypoint Studio 6.x or below. +
If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--

Anypoint Studio displays a welcome message when it loads for the first time. +
Click *Get Started* to start using Anypoint Studio.


== See Also

* xref:studio-xulrunner-unx-task.adoc[To Configure XULRunner as Studio's Default Layout Engine (Mac OSx)]
* xref:jdk-requirement-lnx-worflow.adoc[To Configure Java JDK (Linux)]
* xref:studio-configure-vm-task-unx.adoc[To Configure Studio's Default VM (Mac OSx)]
