= Download and Install Anypoint Studio (Windows)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: jdk-requirement-lnx-worflow.adoc, jdk-requirement-wx-workflow.adoc, jdk-requirement-xos-worflow.adoc, studio-configure-vm-task-lnx.adoc, studio-configure-vm-task-unx.adoc, studio-configure-vm-task-wx.adoc, faq-jdk-requirement.adoc


. Download the Anypoint Studio installation file from the https://www.mulesoft.com/lp/dl/studio[Download Site].
. Extract the Windows installation file into the `C:\` root folder.
** If you are using a Windows antivirus application, ensure that the `plugin/` and `features/` directories are under the _trusted_ category.
. Open the extracted Anypoint Studio.
+
When Studio first runs, the embedded OpenJDK libraries might cause a Windows Security alert. +
Ensure to allow the OpenJDK Platform library from the AdoptOpenJDK publisher through your Windows firewall.
. Click OK to accept the default workspace. +
** If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or later. +
Studio 7.x supports only Mule 4.x projects, because the structure of the project, export format, XML, and scripting language are different than the ones used by Mule 3.x.
