= Downloading and Installing Anypoint Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: to-download-and-install-studio-wx.adoc, to-download-and-install-studio-ox.adoc, to-download-and-install-studio-lx.adoc

== Prerequisites

* Make sure you have the Java SE JDK 8 installed and configured. +
See xref:faq-jdk-requirement.adoc[Configuring your JDK Installation] for instructions.
* Download the Anypoint Studio installation file from the https://www.mulesoft.com/lp/dl/studio[Anypoint Studio Download Site].

[NOTE]
Anypoint Studio 7.x only supports Mule 4.x projects since the structure of the project, export format, XML and scripting language are different.

[[windows]]
== Windows

. Extract the Windows installation file into the `C:\` root folder. +
If you are using a Windows Anti-Virus application, ensure that the `plugin/` and `features/` directories are under the “trusted” category.
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace.
+
[NOTE]
--
You cannot reuse a workspace used by Anypoint Studio 6.x or below. +
If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--

Anypoint Studio displays a welcome message when it loads for the first time. +
Click Get Started to start using Anypoint Studio.


[[osx]]
== OSx

. Extract the Anypoint Studio package and move it to your `/Applications` directory.
. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace. +
When setting a custom path to your workspace, keep in mind that Anypoint Studio does not expand the `~` tilde used in Unix/Linux systems. It is recommended to use the absolute path when defining your workspace.
+
[NOTE]
--
You cannot reuse a workspace used by Anypoint Studio 6.x or below. +
If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--

Anypoint Studio displays a welcome message when it loads for the first time. +
Click Get Started to start using Anypoint Studio.

[[linux]]
== Linux

[NOTE]
To support some of Studio Themes in Linux, it is recommended to have GTK version 2 installed.

. Open the extracted Anypoint Studio.
. Click OK to accept the default workspace. +
When setting a custom path to your workspace, keep in mind that Anypoint Studio does not expand the `~` tilde used in Unix/Linux systems. It is recommended to use the absolute path when defining your workspace.
+
[NOTE]
--
You cannot reuse a workspace used by Anypoint Studio 6.x or below. +
If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--

Anypoint Studio displays a welcome message when it loads for the first time. +
Click Get Started to start using Anypoint Studio.


== See Also
