= Download and Install Anypoint Studio (Linux)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== Before You Begin Installing Anypoint Studio

* To support the Studio Theme on Linux, you must have the GTK version 3 installed.
* Download the Studio installation file from the https://www.mulesoft.com/lp/dl/studio[Download Site].

== Installation

. Open the extracted Anypoint Studio.
. Choose a directory for extraction. You can choose a directory under your home directory, such as `~/anypoint-studio`.
. Open a terminal window.
. Navigate to the download directory.
. Use the `tar` command to extract the contents of the archive file. For example, if the file name is *anypoint-studio-7.21.0.tar.gz*, run:
+
----
`tar -xvzf anypoint-studio-7.21.0.tar.gz -C ~/anypoint-studio`
----
+
This command extracts the contents of the archive to the `~/anypoint-studio` directory.
. Go to the extracted directory.
. Run Studio.
. Click *OK* to accept the default workspace.

== Workspaces Considerations

* You must use an absolute path when defining your workspace because Studio doesn't expand the `~` tilde used in Unix and Linux systems.
* If you choose to use an existing workspace, the workspace must be created with Studio 7.0 or later. Studio 7.x supports Mule 4.x projects. The structure of the project, export format, XML, and scripting language are different from the ones used by Mule 3.x.
