= What’s New in Studio

Anypoint Studio 7.15.0 improves the developer experience by enhancing Studio performance for Windows users, improves the asset-import experience, and adds more CloudHub deployment options.

== Improved Performance for Customers on Windows

Windows users now experience improved performance in Studio by using the built-in tool to exclude Studio from Windows Defender scans.

== Enhanced Experience Importing API Specifications or Fragments

Studio enhances importing experience of API specifications or fragments from Design Center improving the ability to search and provide more details displaying:

* Type of asset
* Date the asset was last updated

== Easy Deployment and Redeployment of a Mule App to Cloudhub 2.0

Users now can deploy and redeploy a Mule app to CloudHub 2.0 even if it has the same name and target as an existing one in CloudHub 2.0. This feature is helpful for redeploying a Mule app after making changes to it.

== Native Support for M1 and M2 Processors

Studio now natively supports Apple M1 and M2 processors.

== Improvements in the User Experience

* Studio now provides more and clearer details in the log if the pom.xml has an error.
* The .mule folder is included in the .gitignore folder so displaying of changes in your project is more accurate.
