
// tag::prereq[]

== Prerequisites

* Make sure you have the Java SE JDK 8 installed and configured.
* Download the Anypoint Studio installation file from the https://www.mulesoft.com/lp/dl/studio[Anypoint Studio Download Site].

[NOTE]
Anypoint Studio 7.x only supports Mule 4.x projects since the structure of the project, export format, XML and scripting language are different.

// end::prereq[]

// tag::vm-argument[]
* The `-vm` option and the installation path must be in separate lines.
* The value must be the full absolute or relative path to the Java executable, not just to the Java home directory.
* The `-vm` option must occur after the other Studio-specific options (such as `-product`, `--launcher.*`, etc), but before the `-vmargs` option, because everything after `-vmargs` is passed directly to the JVM.
// end::vm-argument[]

// tag::tilde-workspace-reuse-note[]
// tag::tilde-note[]
When setting a custom path to your workspace, keep in mind that Anypoint Studio does not expand the `~` tilde used in Unix/Linux systems. It is recommended to use the absolute path when defining your workspace.
+
// end::tilde-note[]
// tag::workspace-reuse[]
[NOTE]
--
You cannot reuse a workspace used by Anypoint Studio 6.x or below. If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--

== Troubleshooting

If Studio fails to load with a *An Error Has Occured* message, follow the instructions below to configure Anypoint Studio to point to your JDK installation as the default VM.
// end::workspace-reuse[]
// end::tilde-workspace-reuse-note[]